/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

/**
 *
 * @author Administrator
 */
public class MultiOntology extends javax.swing.JFrame {

    /**
     * Creates new form MultiOntology
     */
    public static Boolean multiOntology=false;
    public MultiOntology() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        raSingleOntology = new javax.swing.JRadioButton();
        raMulitOntology = new javax.swing.JRadioButton();
        btnSaveOntology = new javax.swing.JButton();
        btnCancelMultiOntology = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(raSingleOntology);
        raSingleOntology.setLabel("single ontology");
        raSingleOntology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raSingleOntologyActionPerformed(evt);
            }
        });

        buttonGroup1.add(raMulitOntology);
        raMulitOntology.setLabel("multi ontology");
        raMulitOntology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raMulitOntologyActionPerformed(evt);
            }
        });

        btnSaveOntology.setLabel("save");
        btnSaveOntology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveOntologyActionPerformed(evt);
            }
        });

        btnCancelMultiOntology.setLabel("cancel");
        btnCancelMultiOntology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelMultiOntologyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(raMulitOntology, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(raSingleOntology, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSaveOntology, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelMultiOntology, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(raSingleOntology)
                .addGap(18, 18, 18)
                .addComponent(raMulitOntology)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveOntology)
                    .addComponent(btnCancelMultiOntology))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveOntologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveOntologyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSaveOntologyActionPerformed

    private void btnCancelMultiOntologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelMultiOntologyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelMultiOntologyActionPerformed

    private void raMulitOntologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raMulitOntologyActionPerformed
        // TODO add your handling code here:
        multiOntology=true;
    }//GEN-LAST:event_raMulitOntologyActionPerformed

    private void raSingleOntologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raSingleOntologyActionPerformed
        // TODO add your handling code here:
        multiOntology=false;
    }//GEN-LAST:event_raSingleOntologyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiOntology.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiOntology.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiOntology.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiOntology.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiOntology().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelMultiOntology;
    private javax.swing.JButton btnSaveOntology;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton raMulitOntology;
    private javax.swing.JRadioButton raSingleOntology;
    // End of variables declaration//GEN-END:variables
}
